#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MyApp.Resource", IsApplication=true)]

namespace MyApp
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "13.2.2.120")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int ic_launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int image1 = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int image10 = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int image11 = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int image12 = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int image13 = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int image14 = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int image15 = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int image16 = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int image17 = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int image18 = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int image19 = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int image2 = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int image3 = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int image4 = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int image5 = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int image6 = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int image7 = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int image8 = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int image9 = 2130837522;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int btnBack = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int btnGallery = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int btnNext = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int btnPrevious = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int btnSlideshow = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int galleryLayout = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int imageCount = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int imageView = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int txtImageNumber = 2130903048;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int activity_gallery = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int activity_main = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int activity_slideshow = 2130968578;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F050000
			public const int ic_launcher = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int ic_launcher_foreground = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int ic_launcher_round = 2131034114;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F060000
			public const int action_settings = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int app_name = 2131099649;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F070000
			public const int AppTheme = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
